### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by zhren711** [Aditya5052/Multi-Camera-Person-Tracking-and-ReID#1]
Thanks for your great work! But when I run the code ,encounter an error which is described as "FileNotFoundError: File is not found at "model_data/models/model.pth" , so where can I get the reid pretrained model?

**Comment by Aditya5052** [comment]
Thanks for pointing this out. Here is the link for the Torchreid model : https://drive.google.com/file/d/1z1yC4dlYsN5OgtlUNHqIMf8VwnWeE4Ty/view?usp=sharing

I have also updated the readme accordingly.
